# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
    hidden: true

  test:
    desc: Run tests for the base crate
    cmds:
      - cargo test --target x86_64-unknown-linux-gnu
